from pathlib import Path

SHORT_WINDOW = "30min"
LONG_WINDOW = "2h"

REJECTED_STATUS = "REJECTED"
SUCCESS_STATUS = "SUCCESS"

WINDOW_WARM_THRESHOLD = 50
BASELINE_WARM_THRESHOLD = 50

DATA_PATH = Path("data/events.csv")

EVALUATION_THRESHOLD_STEPS = 100
